# Generated by Django 3.2.7 on 2021-10-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0002_insert_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('working', 'работает'), ('on_vacation', 'в отпуске'), ('on_sick', 'на больничном'), ('on_time_off', 'в отгуле')], max_length=16, verbose_name='статус сотрудника')),
                ('rome_status', models.CharField(choices=[('tubicen', 'Тубицен'), ('evocatus', 'Эвокат'), ('duplicarius', 'Дупликарий'), ('praefectus_castrorum', 'Префект лагеря'), ('laticlavius', 'Латиклавий'), ('legatus', 'Легат')], default='tubicen', max_length=20, verbose_name='римский статус')),
                ('job_title', models.CharField(max_length=16, verbose_name='должность')),
                ('is_teamlead', models.BooleanField(default=False, verbose_name='Тимлид')),
                ('is_head_of_departament', models.BooleanField(default=False, verbose_name='Руководитель отдела')),
                ('is_remote', models.BooleanField(default=False, verbose_name='удаленный сотрудник')),
                ('telegram', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('vkontakte', models.CharField(blank=True, max_length=64, null=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='о себе')),
                ('photo_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='ссылка на фото')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='начало работы')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='дата увольнение')),
                ('is_fired', models.BooleanField(default=False, verbose_name='уволен')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.departament', verbose_name='Департамент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='employee.employee', verbose_name='Начальник')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.office', verbose_name='офис')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
