# Generated by Django 3.2.7 on 2021-10-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=64, verbose_name='должность'),
        ),
    ]
