# Generated by Django 3.2.7 on 2021-10-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=89661215210),
        ),
    ]
