# Generated by Django 3.2.7 on 2021-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('name', models.CharField(choices=[('android', 'Андройд разработка'), ('ios', 'iOS разработка'), ('frontend', 'Frontend разработка'), ('backend', 'Backend разработка'), ('manager', 'Управление'), ('analytics', 'Аналитика'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('test', 'Тестирование'), ('back', 'Бэкофис'), ('hr', 'HR')], max_length=32)),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('city', models.CharField(choices=[('moscow', 'Moсква'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('ufa', 'Уфа'), ('kalinin', 'Калининград')], max_length=8, verbose_name='город')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
                ('phone', models.PositiveBigIntegerField(verbose_name='контактный номер')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'офис',
                'verbose_name_plural': 'офисы',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
