# Generated by Django 3.2.7 on 2021-10-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('lunch', 'обед'), ('sport', 'спорт'), ('party', 'вечеринка'), ('board_games', 'настольные игры'), ('nature', 'природа')], max_length=16, verbose_name='заголовок')),
                ('photo_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='ссылка на фото')),
                ('place', models.CharField(max_length=32, verbose_name='место встречи')),
                ('dttm', models.DateTimeField(verbose_name='время мероприятия')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='создатель заявки')),
            ],
            options={
                'verbose_name': 'активность',
                'verbose_name_plural': 'активности',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tinder.activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
