# Generated by Django 3.2.7 on 2021-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_alter_likedactivity_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedactivity',
            options={'ordering': ('-created_at',), 'verbose_name': 'понравившаяся активность', 'verbose_name_plural': 'понравившиеся активности'},
        ),
    ]
